export enum Aquisicao {
  MANUTENCAO_E_REPARACAO_DE_VEICULOS_AUTOMOVEIS = 'C01',
  MANUTENCAO_E_REPARACAO_DE_MOTOCICLOS_DE_SUAS_PECAS_E_ACESSORIOS = 'C02',
  ALOJAMENTO_RESTAURACAO_E_SIMILARES = 'C03',
  ATIVIDADES_DE_SALOES_DE_CABELEIREIRO_E_INSTITUTOS_DE_BELEZA = 'C04',
  ATIVIDADES_VETERINARIAS = 'C09',
  AQUISICAOO_DE_PASSES_MENSAIS_PARA_UTILIZACAO_DE_TRANSPORTES_PUBLICOS_COLETIVOS = 'C10',
  EDUCACAO = 'C06',
  IMOVEIS = 'C07',
  LARES = 'C08',
  GINASIOS = 'C11',
  SAUDE = 'C05',
  OUTROS = 'C99',
}
